# Use the official Golang image as the base image
FROM golang:1.20.4

# Set the working directory inside the container
WORKDIR /roomserve

# Copy your Go application code into the container
COPY . .

# Install any dependencies if needed
RUN go mod download

# Run your Go tests
CMD ["go", "test", "./test"]