name: Testing Pipeline

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Run docker compose up
      run: docker compose -f ./test/docker-compose.yml up --exit-code-from test --build
    # - name: Store result of docker compose
    #   run: |
    #     EXIT_CODE=$(docker inspect test-test-1 --format='{{.State.ExitCode}}')
    #     echo $EXIT_CODE

    # - name: Prune docker containers and images
    #   run: docker system prune -f
    # - name: Prune docker volumes
    #   run: docker volume prune -f
    # - name: Exit based on test result
    #   run: exit $EXIT_CODE
  cleanup:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Remove docker containers
        run: docker system prune -f
      - name: Remove docker volumnes
        run: docker volume prune -f

      


