name: Testing Pipeline

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Run docker compose up
      run: exit_code = $(docker compose -f ./test/docker-compose.yml up --exit-code-from test --build)
    - name: Prune docker containers and images
      run: docker system prune -f
    - name: Prune docker volumes
      run: docker volume prune -f
      


