name: Testing Pipeline

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Run docker compose up
      run: docker compose -f ./test/docker-compose.yml up --exit-code-from test --build

  cleanup:
    runs-on: self-hosted
    steps:
      - name: Remove docker containers
        run: docker system prune -f
      - name: Remove docker volumnes
        run: docker volume prune -f

      


